### ISSUE TITLE
which machine you ran the programme on？

### ISSUE THREAD

**Issue by ontheway-arch** [assafbk/mocha_code#1]
Thank you for your outstanding work, may I ask which machine you ran the programme on, I'm using two 3090 for training and found CUDA out of memory.
Do you have a plan to release trained weights？

**Comment by assafbk** [comment]
No problem :)
Our final results ran on an A6000, but most of the time I used two Titan X (with a smaller batch: num_of_images_per_batch=3, num_of_samples_per_image=8).

Yes we will release the trained weights.
