### ISSUE TITLE
Network problems prevented COCO images from being downloaded

### ISSUE THREAD

**Issue by ontheway-arch** [assafbk/mocha_code#2]
发生异常: UnidentifiedImageError
cannot identify image file <_io.BytesIO object at 0x7fa5ddc09cb0>
  File "/data2/xingyc/mocha_code/dataset.py", line 26, in fetch_image
    img = Image.open(BytesIO(response.content))
  File "/data2/xingyc/mocha_code/dataset.py", line 35, in <listcomp>
    batch = [{'image' : COCO.fetch_image(obj['url']), 'caption' : obj['sentences']} for obj in batch]
  File "/data2/xingyc/mocha_code/dataset.py", line 35, in url_coco_collate_fn
    batch = [{'image' : COCO.fetch_image(obj['url']), 'caption' : obj['sentences']} for obj in batch]
  File "/data2/xingyc/mocha_code/vlm_rlhf.py", line 282, in <module>
    for idx, batch in enumerate(tqdm(data_loader_train)):
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fa5ddc09cb0>

in config，where do I download the following two files? I didn't find it on the official website (https://cocodataset.org/#download)
    "coco_annotations_train": "./coco-karpathy/data/train-00000-of-00001.parquet",
    "coco_annotations_val": "./coco-karpathy/data/validation-00000-of-00001.parquet",

**Comment by assafbk** [comment]
git lfs clone https://huggingface.co/datasets/yerevann/coco-karpathy
