### ISSUE TITLE
About ICC code

### ISSUE THREAD

**Issue by chenyf2022** [assafbk/mocha_code#4]
ICC: Quantifying Image Caption Concreteness for Multimodal Dataset Curation, Hello authors,

I would like to inquire if the code for this paper is open source? I am currently researching a related topic and may need to utilize some portions of it. My email address is chenyf339@mail2.sysu.edu.cn. Best regards.

**Comment by assafbk** [comment]
@moranyanuka would know best.

**Comment by moranyanuka** [comment]
@chenyf2022  Thanks for taking interest in our work! We do plan to release the code for ICC soon, but I still have some cleanups to do. However, I released for now the ICC model [here](https://github.com/moranyanuka/icc_code), hope it helps.

**Comment by chenyf2022** [comment]
> @chenyf2022 感谢您对我们的工作感兴趣！我们确实计划很快发布 ICC 的代码，但我仍然有一些清理工作要做。不过，我现在[在这里](https://github.com/moranyanuka/icc_code)发布了 ICC 模型，希望对您有所帮助。

thanks you！
